# -*- coding: utf-8 -*-
"""Copia di lez_8_Inpainting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vvGFBFWNjAvVdEB_jT0FDkI_5iLXUUny
"""

from skimage.io import imread
import numpy as np
from scipy.io import loadmat
from matplotlib import pyplot as plt
import time
import os

from google.colab import drive
drive.mount('/content/drive')
os.chdir('/content/drive/MyDrive/Uni/ImageProcessing')
rootfolder = 'Colab Students - Assignments/data'

"""Useful function for plot a 2D dictionary"""

def get_dictionary_img(D):
    M, N = D.shape
    p = int(round(np.sqrt(M)))
    nnn = int(np.ceil(np.sqrt(N)))
    bound = 2
    img = np.ones((nnn*p+bound*(nnn-1), nnn*p+bound*(nnn-1)))
    for i in range(N):
        m = np.mod(i, nnn)
        n = int((i-m)/nnn)
        m = m * p + bound * m
        n = n * p + bound * n
        atom = D[:, i].reshape((p, p))
        if atom.min() < atom.max():
            atom = (atom - atom.min()) / (atom.max() - atom.min())
        img[m: m + p, n: n + p] = atom

    return img

"""Define a function that implements the OMP"""

from numpy._core.fromnumeric import argmin

def OMP(s, D, L, tau, maxiter = 10000):
  M,N = D.shape
  x = np.zeros(N)
  i = 0
  r = s.copy()
  w = []
  while np.linalg.norm(r) > tau and len(w) < L and i < maxiter:

        # Match
        epsilon = np.abs(np.dot(D.T, r))
        jstar = np.argmax(epsilon)

        # Update w
        if jstar not in w:
            w.append(jstar)

        # Least squares update
        D_omega = D[:, w]
        x_omega, _, _, _ = np.linalg.lstsq(D_omega, s, rcond=None)

        #sparse vector and residual
        x = np.zeros(N)
        x[w] = x_omega
        r = s - np.dot(D, x)

        i += 1

  return x

"""Load the image and rescale it in $[0,1]$"""

img = imread(f'{rootfolder}/peppers256.png') / 255
#img = imread(f'{rootfolder}/barbara.png') / 255
#img = imread(f'{rootfolder}/Lena512.png') / 255
# img = imread('/content/drive/MyDrive/Uni/ImageProcessing/MyImages/foto_pasquetta')/255

imsz = img.shape

# patch size
p = 8

# number of elements in the patch
M = p ** 2

"""Corrupt the image with white gaussian noise"""

sigma_noise = 20/255
noisy_img = img + sigma_noise * np.random.randn(*img.shape)

"""Percentage of removed pixel"""

perc_of_removed_pixels = 0.25

"""Arbitrarily remove pixels setting them to zero"""

from numpy.random import shuffle
# create a vector with all the indexes of the image
idx = np.arange(imsz[0] * imsz[1])

# shuffle it and take the target percentage of indexes
np.random.shuffle(idx)

# the mask is 0 for the chosen idx, 1 elsewhere
msk = np.ones_like(idx, dtype=int)
msk[idx[:int(perc_of_removed_pixels * len(idx))]] = 0
msk = msk.reshape(imsz[0],imsz[1])

# apply the mask: set to 0 some elements in the noisy image
noisy_img = noisy_img * msk

"""Compute the psnr of the noisy input"""

psnr_noisy = 10 * np.log10(1 / np.mean(np.square(noisy_img - img)))

fig, ax = plt.subplots(1, 2, figsize=(20, 10))
ax[0].imshow(noisy_img, cmap='gray')
ax[0].set_title(f'Noisy image before inpainting, PSNR = {psnr_noisy:.2f}')

ax[1].imshow(msk, cmap='gray')
ax[1].set_title(f'Dead pixels')

"""Load and display the dictionary learned from patches"""

D = loadmat(f'{rootfolder}/dict_nat_img.mat')['D']

# add a constant atom to D, KSVD was trained over patches with zero mean - and normalize it
# UPDATE D
DC_atom = np.ones((M, 1)) / np.sqrt(M)
D = np.concatenate((DC_atom, D), axis=1)

# display the dictionary
D_img = get_dictionary_img(D)

plt.figure(figsize=(10,10))
plt.imshow(D_img, cmap='gray')

"""Inpainting
----------

"""

# SET stopping criteria of OMP
# orthogonal matching pursuit uses sparsity and errors as stopping criteria
L = int(M / 2)

# initialize the estimated image
img_hat = np.zeros_like(img)

# initialize the weight matrix
weights = np.zeros_like(img)

# define the step (=p for non overlapping paches)
STEP = 4 # STEP = 1 might be very time consuming, start with larger STEP

"""Operate patchwise"""

for i in range(0, imsz[0] - p + 1, STEP):
    for j in range(0, imsz[1] - p + 1, STEP):
        # extract patch
        s = noisy_img[i: i + p, j: j + p].reshape(M)
        m = msk[i:i+p , j:j+p].reshape(M)

        # design projection operator
        known_idx = np.nonzero(m)[0]
        PD = D[known_idx, :]
        s_known = s[known_idx]

        norms = np.linalg.norm(PD, axis=0)
        norms[norms < 1e-8] = 1 # Evita la divisione per zero
        PD = PD / norms

        # dynamic tolerance
        tau = sigma_noise * np.sqrt(len(known_idx))

        # sparse coding (OMP)
        x = OMP(s_known, PD, L, tau)
        x = x/norms

        # reconstruction
        s_hat = np.dot(D, x)
        patch_hat = s_hat.reshape((p, p))

        # weights for aggregation
        w = 1

        # update estimated image and weight matrix
        img_hat[i:i+p, j:j+p] += patch_hat
        weights[i:i+p, j:j+p] += w

"""Normalize the estimated image with the computed weights"""

img_hat = img_hat / weights
img_hat = np.clip(img_hat, 0, 1)

"""Compute the psnr of the estimated image"""

psnr_hat = 10 * np.log10(1 / np.mean(np.square(img_hat - img)))

fig, ax = plt.subplots(1, 3, figsize=(20, 10))

ax[0].imshow(img, cmap='gray')
ax[0].set_title(f'Original image')

ax[1].imshow(noisy_img, cmap='gray')
ax[1].set_title(f'Corrupted image, PSNR = {psnr_noisy:.2f}')

ax[2].imshow(img_hat, cmap='gray')
ax[2].set_title(f'Estimated Image,\nPSNR = {psnr_hat:.2f}')